### ISSUE TITLE
Incorrect cross-product constraint

### ISSUE THREAD

**Issue by curtisbright** [BrianLi009/PhysicsCheck#4]
https://github.com/BrianLi009/PhysicsCheck/blob/0074319fcfb9a47f398b37fbe6cb6295f4480bfd/embedability/main.py#L198-L200

The orthogonality constraint should be a single constraint and not three separate constraints.  Also, I thought you were going to remove the nested cross-products from the encoding to match the paper's description.  Generating constraints 1–4 from the paper should be simple; it is best if the constraints are simple as it makes it less likely that they are encoded incorrectly.

**Comment by BrianLi009** [comment]
I have changed it to one single constraint, thanks for catching this.

I did remove the nested cross-products for all the cross product relations, but when we define each vector, we are using the nested relations. 

If we remove the nested relations for vector definition, Z3 slows down a bit. For example, some graph that didn't timeout on the first assignment before starts to timeout, showing that the solving is indeed slower. It's a bit of a trade off for clarity I would say.

Just to demo what I'm talking about about, I uploaded a Z3 example script for an order 10 graph: https://github.com/BrianLi009/PhysicsCheck/blob/master/embedability/z3_output_example.py

**Comment by curtisbright** [comment]
If you don't nest cross products and instead use the already-defined vectors you are not adding any extra complexity to the constraints, so it would be surprising if Z3 slows down significantly -- and that could be indicative of a bug.

Some graphs timing out on the first assignment does not imply that the solving is slower.  There is a lot of randomness in satisfiability searches so you need to run many trials.  For example, perhaps some graphs formerly timed out on the first assignment and no longer do.

**Comment by BrianLi009** [comment]
Okay I'm looking more into it, will keep you updated on this, thanks.

**Comment by BrianLi009** [comment]
I found the bug when I was trying to eliminate the nested cross product, the bug lies in the way the script inteprets the ortho relations without nested cross product, and does not influence the original code. I fixed the bug, and got rid of nested cross product completely. I have tested the new script on order 10 and got the correct result. I'm testing it on order 11 now for safety.

See the z3 script example now: https://github.com/BrianLi009/PhysicsCheck/blob/master/embedability/z3_output_example.py

**Comment by curtisbright** [comment]
Hi Brian, it's good that you found it the bug, although I don't understand what it was.  The issue is that it is difficult to verify that this code is doing the right thing, even though the constraints in the paper are quite straightforward.

Even before getting to the generation script it looks like the encoding still doesn't follow the paper.  For example, why is $V_i\neq V_j$ encoded as $V_i\times V_j\neq0$?

I also only see one dot product constraint in the example which seems wrong.  Perhaps you are not generating dot product constraints for edges part of a triangle (though it is safe to do so, of course) but regardless I would still expect there to be many edges which are not part of a triangle.

**Comment by BrianLi009** [comment]
Hi Curtis,

Only one dot product constraint is correct. This is not a KS graph, it's just a random squarefree graph with 10 vertices. I have attached a quick drawing of the graph, and you can see that all the edges are encoded in the constraint.

I will update the embedability section on the paper tonight, right now it is not super clear that we are not encoding ALL dot product relations, and I'll make sure the constraints are consistent with our implementation.

![image](https://user-images.githubusercontent.com/40159724/187813098-53d1727b-ee61-462b-852f-ec3e6a2efc49.png)

**Comment by curtisbright** [comment]
I'm confused about the encoding, then.  I only see 1 triangle in that graph so I would expect just one cross-product constraint.
Edit: I think I see now, vertex 4 would be the cross product of vertex 8 and vertex 7.  Vertex 7 would be the cross product of vertex 4 and vertex 3, etc.

**Comment by curtisbright** [comment]
Since vertex 2 appears in no cross-product constraints shouldn't you also have the norm condition $V_2\cdot V_2=1$?

If vertex $i$ is connected to both vertex $j$ and vertex $k$ it may just be easier to generate the constraint $V_i=\pm(V_j\times V_k)$ without worrying about dot products at all.

Also, I still don't understand why $V_i\neq V_j$ is encoded as $V_i\times V_j\neq0$.

**Comment by BrianLi009** [comment]
Is the norm condition necessary? As long as the orthogonality constraints are encoded, we can always project a vector that is too long/short onto the 1-sphere.

This is the reason why we have $V_i\times V_j\neq0$, since we are restricting them to be non-colinear due to the lack of norm condition.

**Comment by BrianLi009** [comment]
I will add the norm condition in for clarity, it shouldn't affect the sat and unsat result. I'm not sure if we should change $V_i\times V_j\neq0$ to $V_i\neq V_j$, since if two vectors live on the equator, they can be nonequal but colinear, and we want to prevent that.

**Comment by curtisbright** [comment]
That's right, the solver may be able to cope with no norm specified, but it shouldn't hurt to add it.

You're right that using $V_i\neq V_j$ needs additional symmetry breaking constraints.  We used to have them, but it looks like at some point they were removed.  They were $z_i=0\rightarrow y_i\geq0$ and $V_i\neq(0,0,-1)$.

**Comment by BrianLi009** [comment]
Can I make the norm constraint as a parameter that we can call? The reason is, by adding norm constraint to "free vectors", some graph is solved as quickly as before, while some experiences a slowdown. I am currently running it on all order-10 squarefree graph, and we are seeing an increase in total solving time out of all graphs.

The norm constraint is helpful when we want to see the actual vector value, but not as much when we are determining if a graph is embedable.

**Comment by curtisbright** [comment]
How much of a difference in running time is it?  Sure, you could add it as a parameter.  Just make sure the encoding described in the paper is the one actually used in the results section.
